name: Deploy to HuggingFace

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Prepare HF deployment files
        run: |
          # Rename the Hugging Face app file to app.py
          cp hf_app.py app.py
          
          # Rename requirements file
          cp requirements_hf.txt requirements.txt
          
          # Ensure HF configuration is set up
          mkdir -p .huggingface
          cp huggingface-space.yml .huggingface/space.yml
      
      - name: Push to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_SPACE_NAME: cyberforge-dashboard
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          
          # Add all files
          git add .
          git commit -m "Prepare files for HF deployment"
          
          # Push to Hugging Face
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME main