[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#E74C3C"
backgroundColor = "#1A1A1A"
secondaryBackgroundColor = "#2C3E50"
textColor = "#ECF0F1"
font = "sans serif"

[global]
developmentMode = false
